FROM rust:1.75-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Installer cargo-watch pour le hot reload
RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./
RUN cargo fetch

COPY . .

EXPOSE 8092

CMD ["cargo", "watch", "-x", "run"]