FROM golang:1.25-alpine
WORKDIR /app
ENV GOTOOLCHAIN=auto
RUN apk add --no-cache git wget gcc g++ musl-dev
ENV CGO_ENABLED=1
COPY go.mod go.sum ./
RUN go mod download
COPY . .
EXPOSE 8055
ENV PORT=8055
CMD ["go", "run", "."]
