FROM golang:1.21-alpine

WORKDIR /app

RUN apk add --no-cache git

# Installation de Air avec une version spécifique compatible
RUN go install github.com/cosmtrek/air@v1.42.0

# Copie des fichiers de dépendance
COPY go.mod go.sum ./
RUN go mod download

# Copie du reste des fichiers source
COPY . .

EXPOSE 8081

# Lancement avec Air pour le hot reload
CMD ["air", "-c", ".air.toml"]